apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-datadog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  sources:
    # Helm chart for Datadog agent
    - repoURL: ssh://git@github.com/tkuipers/homelab.git
      targetRevision: main
      path: clusters/homelab/infrastructure/datadog/helm-chart-datadog
      helm:
        valueFiles:
          - values.yaml

    # Kustomize for namespace and ExternalSecret
    - repoURL: ssh://git@github.com/tkuipers/homelab.git
      targetRevision: main
      path: clusters/homelab/infrastructure/datadog

  destination:
    server: https://kubernetes.default.svc
    namespace: datadog

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

