apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-nvidia-device-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    repoURL: ssh://git@github.com/tkuipers/homelab.git
    targetRevision: main
    path: clusters/homelab/infrastructure/nvidia-device-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
