apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  sources:
    # Helm chart for Authentik
    - repoURL: ssh://git@github.com/tkuipers/homelab.git
      targetRevision: main
      path: clusters/homelab/infrastructure/authentik/helm-chart-authentik
      helm:
        valueFiles:
          - values.yaml
    # Additional resources (namespace, external secrets, ingress, postgresql, redis)
    - repoURL: ssh://git@github.com/tkuipers/homelab.git
    targetRevision: main
    path: clusters/homelab/infrastructure/authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
