---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-admin-credentials
  namespace: guacamole
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: guacamole-admin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        admin-password: "{{ .admin_password }}"
  data:
  - secretKey: admin_password
    remoteRef:
      key: "Guacamole Admin Credentials"
      property: "password" 