apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - guacamole-credentials-external-secret.yaml
  - postgres-credentials-external-secret.yaml
  - postgres-persistent-volume.yaml
  - postgresql.yaml
  - guacd.yaml
  - guacamole.yaml
  - ingress.yaml 