---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-postgres-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /var/lib/guacamole-postgres  # Directory on the node for PostgreSQL data 