---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-postgres-credentials
  namespace: guacamole
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: guacamole-postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        postgres-password: "{{ .postgres_password }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        database: "{{ .database }}"
  data:
  - secretKey: postgres_password
    remoteRef:
      key: "Guacamole PostgreSQL Credentials"
      property: "postgres_password"
  - secretKey: username
    remoteRef:
      key: "Guacamole PostgreSQL Credentials"
      property: "username"
  - secretKey: password
    remoteRef:
      key: "Guacamole PostgreSQL Credentials"
      property: "password"
  - secretKey: database
    remoteRef:
      key: "Guacamole PostgreSQL Credentials"
      property: "database" 