apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: umami
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: umami-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres_password
    remoteRef:
      key: Umami Credentials
      property: postgres_password
  - secretKey: app_secret
    remoteRef:
      key: Umami Credentials
      property: app_secret
  - secretKey: database_url
    remoteRef:
      key: Umami Credentials
      property: database_url

