apiVersion: v1
kind: Service
metadata:
  name: umami-postgres
  namespace: umami
  labels:
    app: umami-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: umami-postgres

