apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # homepage - now managed by ArgoCD
  # - timemachine/
  # - monitoring/
  # - guacamole/
  # - pterodactyl/
  - mediacenter/
  # - ml/
