apiVersion: v2
name: authentik
description: Helm chart for Authentik SSO
type: application
version: 1.0.0
appVersion: "2025.10.3"

dependencies:
  - name: authentik
    version: 2025.10.3
    repository: https://charts.goauthentik.io

