apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # metallb, cert-manager, ingress-nginx now managed by ArgoCD
  - ./metrics-server
  - ./aws-ip-updater
  - ./external-dns
  - ./nfs-provisioner
  - ./monitoring
  - ./local-path-provisioner
