apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: aws-ip-updater
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: aws-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
        AWS_REGION: "{{ .region }}"
        HOSTED_ZONE_ID: "{{ .hosted_zone_id }}"
        RECORD_NAME: "{{ .record_name }}"
  data:
  - secretKey: access_key_id
    remoteRef:
      key: "AWS Dynamic DNS Credentials"
      property: "access_key_id"
  - secretKey: secret_access_key
    remoteRef:
      key: "AWS Dynamic DNS Credentials"
      property: "secret_access_key"
  - secretKey: region
    remoteRef:
      key: "AWS Dynamic DNS Credentials"
      property: "region"
  - secretKey: hosted_zone_id
    remoteRef:
      key: "AWS Dynamic DNS Credentials"
      property: "hosted_zone_id"
  - secretKey: record_name
    remoteRef:
      key: "AWS Dynamic DNS Credentials"
      property: "record_name" 