apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: default
spec:
  type: ExternalName
  externalName: 192.168.1.152 # eg example.example.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-expose
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP" #important
    # cert-manager.io/cluster-issuer: lets-encrypt
spec:
  rules:
  - host: sonar.mushu.tkuipers.ca # eg external-service.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service
            port:
              number: 8989
  # tls:
  # - hosts:
  #   - sonar.mushu.tkuipers.ca
  #   secretName: microbot-ingress-tls