apiVersion: v2
name: cert-manager
description: Helm chart for cert-manager
type: application
version: 1.16.4
appVersion: "1.16.4"

dependencies:
  - name: cert-manager
    version: v1.21.1
    repository: https://charts.jetstack.io

