# StorageClass for Control Plane NFS Server (2.2Ti capacity)
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-controlplane
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server-controlplane.nfs-servers.svc.cluster.local
  share: /nfsshare
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
# StorageClass for Worker NFS Server (1Ti capacity)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-worker
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-server-worker.nfs-servers.svc.cluster.local
  share: /nfsshare
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true 