# Test PVC to validate NFS storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-controlplane
  namespace: nfs-servers
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-controlplane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-worker
  namespace: nfs-servers
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-worker 