apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
  - secretKey: access-key-id
    remoteRef:
      key: "AWS Credentials"
      property: access_key_id
  - secretKey: secret-access-key
    remoteRef:
      key: "AWS Credentials"
      property: secret_access_key

