# Listen on this interface
interface=eth0

# DHCP range and lease time
dhcp-range=172.16.0.50,172.16.0.150,12h

# Gateway
dhcp-option=option:router,172.16.0.1

# DNS
dhcp-option=option:dns-server,172.16.0.1

# Sidero will handle TFTP services. We are just pointing clients to it.
# Set TFTP root directory
# tftp-root=/srv/tftp

# This tells dnsmasq to look for the ipxe.efi file in the tftp-root
# for clients that are not already using iPXE.
dhcp-boot=ipxe.efi

# Detect iPXE clients (who identify themselves with DHCP option 175)
dhcp-match=set:ipxe,175

# For clients that are already running iPXE, chainload to the Sidero
# controller's iPXE script. The IP address should be this server's IP.
dhcp-boot=tag:ipxe,http://172.16.0.2:8081/ipxe

# Static lease for the Telus router
dhcp-host=d4:86:60:21:5d:4c,172.16.0.3,Telus

# Static IP for the Dell R620 control plane node
dhcp-host=bc:30:5b:f0:bf:04,172.16.0.50 