apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-dreame-vacuum
  namespace: homeassistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: homeassistant-dreame-vacuum
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: "Dreame Vacuum"
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "Dreame Vacuum"
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: country
      remoteRef:
        key: "Dreame Vacuum"
        property: country
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
