apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authentik-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: secret_key
      remoteRef:
        key: "Authentik Credentials"
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: bootstrap_password
      remoteRef:
        key: "Authentik Credentials"
        property: bootstrap_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: bootstrap_token
      remoteRef:
        key: "Authentik Credentials"
        property: bootstrap_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

