apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-chart-secret-sync
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: infrastructure-authentik
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    # Secret key
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: "Authentik Credentials"
        property: secret_key
    # Bootstrap configuration
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: "Authentik Credentials"
        property: bootstrap_password
    - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
      remoteRef:
        key: "Authentik Credentials"
        property: bootstrap_token
    # PostgreSQL connection
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: "Authentik Credentials"
        property: postgresql_host
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: "Authentik Credentials"
        property: postgresql_port
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: "Authentik Credentials"
        property: postgresql_db
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: "Authentik PostgreSQL"
        property: username
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: "Authentik PostgreSQL"
        property: password
    # Redis connection
    - secretKey: AUTHENTIK_REDIS__HOST
      remoteRef:
        key: "Authentik Credentials"
        property: redis_host

