apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgresql-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authentik-postgresql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: "Authentik PostgreSQL"
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "Authentik PostgreSQL"
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

