apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        storage-encryption-key: "{{ .storage_encryption_key }}"
        session-secret: "{{ .session_secret }}"
        jwt-secret: "{{ .jwt_secret }}"
        oidc-hmac-secret: "{{ .oidc_hmac_secret }}"
        oidc-issuer-private-key: "{{ .oidc_issuer_private_key }}"
        argocd-client-secret: "{{ .argocd_client_secret }}"
        argocd-client-secret-hash: "{{ .argocd_client_secret_hash }}"
        users_database.yml: |
          ---
          users:
            tkuipers:
              displayname: "T. Kuipers"
              password: "{{ .user_password_hash }}"
              email: tkuipers123@gmail.com
              groups:
                - admins
                - users
  data:
    - secretKey: storage_encryption_key
      remoteRef:
        key: "Authelia Credentials"
        property: storage_encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: session_secret
      remoteRef:
        key: "Authelia Credentials"
        property: session_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jwt_secret
      remoteRef:
        key: "Authelia Credentials"
        property: jwt_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: user_password_hash
      remoteRef:
        key: "Authelia Credentials"
        property: user_password_hash
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: oidc_hmac_secret
      remoteRef:
        key: "Authelia Credentials"
        property: oidc_hmac_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: oidc_issuer_private_key
      remoteRef:
        key: "Authelia Credentials"
        property: oidc_issuer_private_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: argocd_client_secret
      remoteRef:
        key: "Authelia Credentials"
        property: argocd_client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: argocd_client_secret_hash
      remoteRef:
        key: "Authelia Credentials"
        property: argocd_client_secret_hash
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

