apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        storage-encryption-key: "{{ .storage_encryption_key }}"
        jwt-secret: "{{ .jwt_secret }}"
        # Password hash for user tkuipers
        user-password-hash: "{{ .user_password_hash }}"
  data:
    - secretKey: storage_encryption_key
      remoteRef:
        key: "Authelia Credentials"
        property: storage_encryption_key
    - secretKey: jwt_secret
      remoteRef:
        key: "Authelia Credentials"
        property: jwt_secret
    - secretKey: user_password_hash
      remoteRef:
        key: "Authelia Credentials"
        property: user_password_hash

