apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - external-secret.yaml
  - configmap.yaml
  - branding-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

