apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: authelia
data:
  users_database.yml: |
    ---
    users:
      tkuipers:
        displayname: "T. Kuipers"
        password: "$argon2id$v=19$m=65536,t=3,p=4$PLACEHOLDER_REPLACE_IN_SECRET"
        email: tkuipers123@gmail.com
        groups:
          - admins
          - users

