apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pterodactyl-credentials
  namespace: pterodactyl
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: pterodactyl-credentials
    creationPolicy: Owner
  data:
  - secretKey: app-key
    remoteRef:
      key: "Pterodactyl Panel"
      property: app-key
  - secretKey: database-password
    remoteRef:
      key: "Pterodactyl Panel"
      property: database-password
  - secretKey: mysql-root-password
    remoteRef:
      key: "Pterodactyl Panel"
      property: mysql-root-password 