apiVersion: v1
kind: Service
metadata:
  name: decision
  namespace: stocks
  labels:
    app: stocks-decision
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: stocks-decision
