apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: stocks
  labels:
    app: stocks-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stocks-redis
  template:
    metadata:
      labels:
        app: stocks-redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: omen-worker1
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
