---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: monitoring-credentials-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data:
        admin-user: "{{ .grafana_user }}"
        admin-password: "{{ .grafana_password }}"
  data:
  - secretKey: grafana_user
    remoteRef:
      key: "Monitoring Stack Credentials"
      property: "grafana_user"
  - secretKey: grafana_password
    remoteRef:
      key: "Monitoring Stack Credentials"
      property: "grafana_password"

