apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repo.yaml
  - credentials-external-secret.yaml
  - release.yaml
  - ingress.yaml
  - timemachine-servicemonitor.yaml
  - nvidia-dcgm-exporter.yaml
  - loki-stack-release.yaml
  - grafana-helm-repository.yaml
  - loki-datasource.yaml
  - application-servicemonitors.yaml
  - arr-api-extractor-job.yaml
  - exportarr-deployment.yaml
  - grafana-dashboards.yaml
  - pod-monitors.yaml
  - prometheus-rules.yaml 