apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: ">=4.0.0"
  install:
    createNamespace: true
  targetNamespace: ingress-nginx
  values:
    tcp:
      "445": "timemachine/timemachine:445"
    controller:
      service:
        type: LoadBalancer
      ingressClassResource:
        name: nginx
        enabled: true
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
        certManager:
          enabled: false
        annotations:
          nginx.ingress.kubernetes.io/enable-annotation-validation: "false"
        failurePolicy: Ignore
      config:
        strict-validate-path-type: "false"
    rbac:
      create: true
      scope: false 