apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airvpn-credentials
  namespace: mediacenter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: airvpn-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: private_key
      remoteRef:
        key: "AirVPN"
        property: private_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: preshared_key
      remoteRef:
        key: "AirVPN"
        property: preshared_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: addresses
      remoteRef:
        key: "AirVPN"
        property: addresses
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: server_country
      remoteRef:
        key: "AirVPN"
        property: server_country
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: forwarded_port
      remoteRef:
        key: "AirVPN"
        property: forwarded_port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
