apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: mediacenter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bazarr.tkuipers.ca
    secretName: bazarr-tls
  rules:
  - host: bazarr.tkuipers.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767

