apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-credentials
  namespace: mediacenter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: jellyseerr-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: oidc-client-secret
      remoteRef:
        key: "Authelia Credentials"
        property: jellyseerr_client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
