apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: mediacenter
spec:
  selector:
    app: jellyseerr
  ports:
  - name: http
    port: 5055
    protocol: TCP
    targetPort: http

