apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jellyfin-media-pvc.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - jellyfin-ingress.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - prowlarr-ingress.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - sonarr-ingress.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
  - radarr-ingress.yaml
  - bazarr-deployment.yaml
  - bazarr-service.yaml
  - bazarr-ingress.yaml
  - transmission-credentials-external-secret.yaml
  - airvpn-credentials-external-secret.yaml
  - transmission-deployment.yaml
  - transmission-service.yaml
  - transmission-ingress.yaml
  - transmission-cleanup-cronjob.yaml
  - sabnzbd-deployment.yaml
  - sabnzbd-service.yaml
  - sabnzbd-ingress.yaml
  - arr-integration-job.yaml

