apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jellyfin-media-pvc.yaml
  - jellyfin-deployment.yaml
  - jellyfin-service.yaml
  - jellyfin-ingress.yaml

