apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: mediacenter
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sonarr.tkuipers.ca
    secretName: sonarr-tkuipers-ca-tls
  rules:
  - host: sonarr.tkuipers.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989

