apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dell-r620
  resources:
    requests:
      storage: 5Gi

