apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: mediacenter
spec:
  selector:
    app: transmission
  ports:
  - name: webui
    port: 9091
    targetPort: 9091
  - name: tcp-listen
    port: 51413
    targetPort: 51413
    protocol: TCP
  - name: udp-listen
    port: 51413
    targetPort: 51413
    protocol: UDP

