apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission-credentials
  namespace: mediacenter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: transmission-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: "Transmission"
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "Transmission"
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
