apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airvpn-credentials
  namespace: polymarket-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: airvpn-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: private_key
      remoteRef:
        key: "AirVPN"
        property: private_key
    - secretKey: preshared_key
      remoteRef:
        key: "AirVPN"
        property: preshared_key
    - secretKey: addresses
      remoteRef:
        key: "AirVPN"
        property: addresses
    - secretKey: server_country
      remoteRef:
        key: "AirVPN"
        property: server_country
