apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-oidc-secret
  namespace: actual
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: actual-oidc-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.json: |
          {
            "openId": {
              "discoveryURL": "https://auth.tkuipers.ca",
              "client_id": "actual-budget",
              "client_secret": "{{ .clientSecret }}",
              "server_hostname": "https://budget.tkuipers.ca",
              "authMethod": "openid"
            }
          }
  data:
    - secretKey: clientSecret
      remoteRef:
        key: Authelia Credentials
        property: actual_budget_client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

