apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: actual
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-omen-worker1
  resources:
    requests:
      storage: 5Gi
