apiVersion: v2
name: datadog
description: Umbrella chart for Datadog Agent
type: application
version: 1.0.0
appVersion: "7.60.0"

dependencies:
  - name: datadog
    version: "3.242.0"
    repository: "https://helm.datadoghq.com"

