apiVersion: v2
name: csi-driver-smb
description: Helm chart for SMB CSI Driver
type: application
version: 1.16.0
appVersion: "1.16.0"

dependencies:
  - name: csi-driver-smb
    version: v1.16.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts

