apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-api-keys
  namespace: datadog
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: datadog-api-keys
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: Datadog API Keys
        property: api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: app-key
      remoteRef:
        key: Datadog API Keys
        property: app_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
