apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-depl
spec:
  selector:
    matchLabels:
      app: webserver-app
  template:
    metadata:
      labels:
        app: webserver-app
    spec:
      containers:
        - name: webserver-app
          image: tkuipers/tkuipers-ca:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
spec:
  selector:
    app: webserver-app
  ports:
  - name: webserver-app
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonar-svc
subsets:
  - addresses:
      - ip: 192.168.1.152
    ports:
      - port: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
spec:
  ports:
    - port: 80
      targetPort: 8989

---
apiVersion: v1
kind: Endpoints
metadata:
  name: radar-svc
subsets:
  - addresses:
      - ip: 192.168.1.152
    ports:
      - port: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: radar-svc
spec:
  ports:
    - port: 80
      targetPort: 7878

---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex-svc
subsets:
  - addresses:
      - ip: 192.168.1.152
    ports:
      - port: 32400
---
apiVersion: v1
kind: Service
metadata:
  name: plex-svc
spec:
  ports:
    - port: 80
      targetPort: 32400

---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-svc
subsets:
  - addresses:
      - ip: 192.168.1.100
    ports:
      - port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-svc
spec:
  ports:
    - port: 80
      targetPort: 8006

---
apiVersion: v1
kind: Endpoints
metadata:
  name: elk-svc
subsets:
  - addresses:
      - ip: 192.168.1.153
    ports:
      - port: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: elk-svc
spec:
  ports:
    - port: 80
      targetPort: 5601
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minecraft-svc
subsets:
  - addresses:
      - ip: 192.168.1.155
    ports:
      - port: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
spec:
  ports:
    - port: 80
      targetPort: 25565
---
apiVersion: v1
kind: Endpoints
metadata:
  name: stocker-svc
subsets:
  - addresses:
      - ip: 192.168.1.200
    ports:
      - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: stocker-svc
spec:
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ariel-depl
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ariel-app
  template:
    metadata:
      labels:
        app: ariel-app
    spec:
      securityContext:
      #   runAsUser: 2000
        fsGroup: 1000
      containers:
      - name: ariel-app
        image: sonatype/nexus3
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: registry-vol
          mountPath: /nexus-data
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: sonatype-registry-data
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sonatypestorage
#   labels:
#     name: sonatypestorage # claim for volume
# spec:
#   storageClassName: sonatypestorage # same storage class as pvc
#   capacity:
#     storage: 40Gi
#   accessModes:
#     - ReadWriteOnce
#   nfs:
#     server: 192.168.1.214 # ip address of nfs server
#     path: "/srv"  # path to directory, make sure directory is available
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-registry-data
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ariel-svc
spec:
  selector:
    app: ariel-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  - name: docker
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.214
  share: /srv/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
