apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nvidia-runtimeclass.yaml
  - nvidia-device-plugin.yaml
  - api-key-external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

