# sidero/servers.yaml
---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  # This name must match the UUID of the discovered server.
  name: 4c4c4544-0038-4310-8036-b1c04f585631
spec:
  # Accept the server to allow it to be used.
  accepted: true

  # Manually provide hardware details so the ServerClass can match it.
  hardware:
    system:
      serialNumber: "18C6XV1"

  # Provide the Baseboard Management Controller (BMC) credentials.
  # This is required for Sidero to control the server's power state via IPMI.
  bmc:
    endpoint: 172.16.0.4
    user: tyler-admin
    pass: water123
---
apiVersion: metal.sidero.dev/v1alpha2
kind: Server
metadata:
  # This name must match the UUID of the discovered server.
  name: 81c94e11-1d4d-80d1-41be-100501472f4a
spec:
  # Accept the server to allow it to be used.
  accepted: true

  # Manually provide hardware details so the ServerClass can match it.
  hardware:
    system:
      serialNumber: "4CE75036HH"

  # BMC information is not available for this server.
  # Sidero might not be able to manage power state. 