# sidero/serverclass-worker.yaml
# This file defines a "class" of servers.
# We are creating a class for our worker nodes.
---
apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: home-infra-worker
spec:
  # Reference the default environment created by Sidero.
  environmentRef:
    name: default
    namespace: sidero-system
  # the server's hardware details. If a server matches all qualifiers,
  # it will be claimed by this ServerClass.
  qualifiers:
    hardware:
      - system:
          serialNumber: "4CE75036HH"
  # After Talos is installed, instruct iPXE to exit so the server
  # can boot from the local disk on the next reboot. This breaks the boot loop.
  bootFromDiskMethod: http-404

  # These patches are applied to the Talos machine configuration when a server
  # from this class is provisioned.
  configPatches:
    - op: replace
      path: /machine/type
      value: worker
    - op: replace
      path: /machine/install/disk
      value: /dev/sdb
      # GRAB IMAGE FROM HERE: https://factory.talos.dev/?platform=metal&target=metal
    - op: replace
      path: /machine/install/image
      value: factory.talos.dev/metal-installer/26124abcbd408be693df9fe852c80ef1e6cc178e34d7d7d8430a28d1130b4227:v1.10.4
    - op: add
      path: /machine/network/hostname
      value: omen-worker1
    - op: replace
      path: /cluster/network/cni
      value:
        name: flannel
    - op: replace
      path: /cluster/proxy
      value:
        disabled: false
    - op: replace
      path: /cluster/extraManifests
      value:
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        - https://github.com/fluxcd/flux2/releases/download/v2.6.3/install.yaml
        - https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
        - https://github.com/external-secrets/external-secrets/releases/latest/download/external-secrets.yaml
    - op: add
      path: /cluster/inlineManifests
      value:
        - name: "onepassword-secretstore"
          contents: |
            apiVersion: external-secrets.io/v1beta1
            kind: SecretStore
            metadata:
              name: onepassword-store
              namespace: external-secrets-system
            spec:
              provider:
                onepassword:
                  connectHost: "http://onepassword-connect:8080"
                  vaults:
                    Homelab: 1
                  auth:
                    secretRef:
                      connectToken:
                        name: "onepassword-connect-token"
                        key: "token"
                        namespace: "external-secrets-system"
        - name: "flux-git-ssh-secret"
          contents: |
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            metadata:
              name: flux-git-ssh
              namespace: flux-system
            spec:
              refreshInterval: 1h
              secretStoreRef:
                name: onepassword-store
                kind: SecretStore
                namespace: external-secrets-system
              target:
                name: flux-git-ssh
                creationPolicy: Owner
                template:
                  type: Opaque
                  data:
                    identity: "{{ .privatekey }}"
                    known_hosts: |
                      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
                      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
                      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Hnqd/xb5TXXEcOC8yeLr1lJfZWprM54v2NjT5cJQGXUMFQv7O8LHCgPFfHF1u7MHJA6IUYL5MMZB2MqK0PrpZ9Tb6hZN1JeG9EGKiuA3WjNrTfVrBwAzJW9+W2XtJZE3nCbQCJt5A
              dataFrom:
                - extract:
                    key: "Homelab Git SSH Key"
                    property: "private key"
        - name: "flux-gitrepository"
          contents: |
            apiVersion: source.toolkit.fluxcd.io/v1
            kind: GitRepository
            metadata:
              name: homelab-repo
              namespace: flux-system
            spec:
              interval: 1m
              url: ssh://git@github.com/tkuipers/homelab.git
              ref:
                branch: main
              secretRef:
                name: flux-git-ssh
        - name: "flux-kustomization"
          contents: |
            apiVersion: kustomize.toolkit.fluxcd.io/v1
            kind: Kustomization
            metadata:
              name: homelab-cluster
              namespace: flux-system
            spec:
              interval: 10m
              path: "./clusters/homelab"
              prune: true
              sourceRef:
                kind: GitRepository
                name: homelab-repo
    - op: add
      path: /machine/kernel
      value:
        modules:
          - name: nvidia
          - name: nvidia_uvm
          - name: nvidia_drm
          - name: nvidia_modeset