apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-dell-r620
  template:
    metadata:
      labels:
        app: nfs-server-dell-r620
    spec:
      nodeSelector:
        kubernetes.io/hostname: dell-r620
      containers:
      - name: nfs-server
        image: ghcr.io/democratic-csi/nfs-server
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
        ports:
        - containerPort: 2049
        volumeMounts:
        - name: export
          mountPath: /export
      volumes:
      - name: export
        hostPath:
          path: /var/persist/nfs-dell-r620
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  selector:
    app: nfs-server-dell-r620
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
