apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-dell-r620
  template:
    metadata:
      labels:
        app: nfs-server-dell-r620
    spec:
      nodeSelector:
        kubernetes.ioio/hostname: dell-r620
      containers:
      - name: nfs-server
        image: gcr.io/k8s-staging-nfs-ganesha/nfs-server
        ports:
        - name: nfs
          containerPort: 2049
        - name: nfs-udp
          containerPort: 2049
          protocol: UDP
        - name: rpcbind
          containerPort: 111
        - name: rpcbind-udp
          containerPort: 111
          protocol: UDP
        - name: mountd
          containerPort: 20048
        - name: mountd-udp
          containerPort: 20048
          protocol: UDP
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          capabilities:
            add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
        args:
        - "-fsid=0"
        - "-grace-time=90"
        - "- Lease-time=90"
        - "-export-addr=0.0.0.0"
        - "/exports"
        volumeMounts:
        - name: export
          mountPath: /exports
      volumes:
      - name: export
        hostPath:
          path: /var/persist/nfs-dell-r620
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  selector:
    app: nfs-server-dell-r620
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
