apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-dell-r620
  template:
    metadata:
      labels:
        app: nfs-server-dell-r620
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: dell-r620
      containers:
      - name: nfs-server
        image: hectorm/nfs-ganesha:latest
        env:
        - name: GANESHA_EXPORT_ID
          value: "1"
        - name: GANESHA_EXPORT
          value: /exports
        - name: GANESHA_PSEUDO
          value: /exports
        - name: GANESHA_ACCESS_TYPE
          value: RW
        - name: GANESHA_SQUASH
          value: "no_root_squash"
        - name: GANESHA_FSAL
          value: VFS
        - name: GANESHA_LOGFILE
          value: STDOUT
        - name: GANESHA_OPTIONS
          value: "NFS_Commit = 0; NFS_Protocols = 4; allow_set_io_flusher_fail = true; "
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
        volumeMounts:
        - name: export
          mountPath: /exports
      volumes:
      - name: export
        hostPath:
          path: /var/persist/nfs-dell-r620
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-dell-r620
  namespace: nfs-provisioner
spec:
  selector:
    app: nfs-server-dell-r620
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
