apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-omen-worker1
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-omen-worker1
  template:
    metadata:
      labels:
        app: nfs-server-omen-worker1
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: omen-worker1
      initContainers:
      - name: setup-mtab
        image: busybox:latest
        command: ['sh', '-c', 'echo -e "/dev/root / ext4 rw,relatime 0 0\n/dev/root /export ext4 rw,relatime 0 0" > /etc/mtab']
        volumeMounts:
        - name: mtab
          mountPath: /etc/mtab
      containers:
      - name: nfs-server
        image: hectorm/nfs-ganesha:latest
        env:
        - name: GANESHA_EXPORT_ID
          value: "1"
        - name: GANESHA_EXPORT
          value: /export
        - name: GANESHA_PSEUDO
          value: /export
        - name: GANESHA_ACCESS_TYPE
          value: RW
        - name: GANESHA_SQUASH
          value: "no_root_squash"
        - name: GANESHA_FSAL
          value: VFS
        - name: GANESHA_LOGFILE
          value: STDOUT
        - name: GANESHA_OPTIONS
          value: "NFS_Commit = 0; NFS_Protocols = 4; allow_set_io_flusher_fail = true; "
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
        volumeMounts:
        - name: export
          mountPath: /export
        - name: mtab
          mountPath: /etc/mtab
          readOnly: true
      volumes:
      - name: export
        hostPath:
          path: /var/persist/nfs-omen-worker1
          type: DirectoryOrCreate
      - name: mtab
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-omen-worker1
  namespace: nfs-provisioner
spec:
  selector:
    app: nfs-server-omen-worker1
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
