apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner-dell-r620
  namespace: nfs-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      version: 4.0.18
  values:
    nodeSelector:
      kubernetes.io/hostname: dell-r620
    nfs:
      server: nfs-server-dell-r620.nfs-provisioner.svc.cluster.local
      path: /export
    storageClass:
      name: nfs-dell-r620
      defaultClass: false
      provisionerName: nfs-storage-dell-r620
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - dell-r620
