apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-credentials
  namespace: nfs-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: samba-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: "NFS Provisioner Samba"
      property: password

