apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: timemachine-credentials
  namespace: timemachine
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: SecretStore
  target:
    name: timemachine-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: timemachine-backup
      property: username
  - secretKey: password
    remoteRef:
      key: timemachine-backup
      property: password 