apiVersion: v1
kind: PersistentVolume
metadata:
  name: timemachine-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/timemachine  # Directory on the node for Time Machine backups 