apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: timemachine
  labels:
    app: timemachine
spec:
  type: ClusterIP
  ports:
  - port: 445
    targetPort: 445
    protocol: TCP
    name: smb
  selector:
    app: timemachine 