apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-git-ssh
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: argocd-git-ssh
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: Homelab Git SSH Key
        property: private key

