apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-git-ssh
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: argocd-git-ssh
    template:
      type: kubernetes.io/ssh-auth
      data:
        identity: "{{ .ssh_private_key }}"
        identity.pub: "{{ .ssh_public_key }}"
        known_hosts: "{{ .known_hosts }}"
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: Homelab Git SSH Key
        property: private_key
    - secretKey: ssh_public_key
      remoteRef:
        key: Homelab Git SSH Key
        property: public_key
    - secretKey: known_hosts
      remoteRef:
        key: Homelab Git SSH Key
        property: known_hosts

