apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Repository configuration
  repositories: |
    - url: ssh://git@github.com/tkuipers/homelab.git
      sshPrivateKeySecret:
        name: argocd-git-ssh
        key: sshPrivateKey
      name: homelab
      type: git

  # Resource tracking method
  application.resourceTrackingMethod: annotation

  # Enable status badge
  statusbadge.enabled: "true"

  # Authelia OIDC configuration
  url: https://argo.tkuipers.ca
  oidc.config: |
    name: Authelia
    issuer: https://auth.tkuipers.ca
    clientID: argocd
    clientSecret: $oidc.authelia.clientSecret
    cliClientID: argocd-cli
    requestedScopes:
      - openid
      - email
      - groups
      - profile
    enableUserInfoGroups: true
    userInfoPath: /api/oidc/userinfo

  # Exclude resources from being managed
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"

