apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-helm-repository.yaml
  - grafana-external-secret.yaml
  - kube-prometheus-stack-release.yaml
  - grafana-ingress.yaml
  - prometheus-ingress.yaml
  - alertmanager-ingress.yaml
  - timemachine-servicemonitor.yaml 