apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-credentials-external-secret.yaml
  - mysql-credentials-external-secret.yaml
  - mysql-config.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-backup-cronjob.yaml
  - training-config.yaml
  - training-cronjob.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
