apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-credentials-external-secret.yaml
  - mysql-credentials-external-secret.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
